apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx-server
  name: nginx-service
  namespace: default
spec:
  selector:
    app: nginx-server
  ports:
  - port: 80
    protocal: TCP
    targetPort: 80
  type: NodePort
